spring.application.name=music
spring.datasource.url=jdbc:postgresql://localhost:5432/music_app
spring.datasource.username=postgres
spring.datasource.password=postgres
cloudinary.cloud_name=dinuhmssz

cloudinary.api_key=374262557777985

cloudinary.api_secret=sfewA-km_mRLJHaZkwLGmn_OED4
spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=50MB

spring.servlet.multipart.max-request-size=50MB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true